# Generated by Django 4.2.10 on 2024-04-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_coupon_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
