# Generated by Django 4.2.10 on 2024-02-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
