# Generated by Django 4.2.10 on 2024-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_newslitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslitter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
