# Generated by Django 4.2.10 on 2024-03-10 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_category_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Post Category'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
    ]
