# Generated by Django 4.2.10 on 2024-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_category_options_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
