# Generated by Django 4.2.10 on 2024-04-29 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
